news_sites:
  elpais:
    url: https://www.elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_title: '.a_hg h1'
      article_body: '.a_w'
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal1:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.titulo a'
      article_title: '.ceh-Opinion h2'
      article_body: '.field-name-body'
  eluniversal2:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce2-Tipo1_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal3:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce3-Tipo1_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal3-2:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce3-Tipo2_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal3-3:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce3-Tipo3_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal3-6:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce3-Tipo6_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal3-7b:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce3-Tipo7b_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal4:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce4-Vertical_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
  eluniversal6:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce6-Tipo1_Titulo a'
      article_title: '.Encabezado-Articulo h1'
      article_body: '.field-name-body'
