news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
  elpais:
    url: https://www.elpais.com
    queries:
      homepage_article_links: '.headline a'
